### ISSUE TITLE
pattern colors don't match reality

### ISSUE THREAD

**Issue by hwanggz0** [kriswiner/IS31FL3194#2]
https://github.com/kriswiner/IS31FL3194/blob/a4e3d77cede73e536f4a38a723b174e8f7eb0be1/IS31FL3194.basic.ino#L218
are you expecting to mix blue color on P1? from the color i would expect to see mixing white color, but somehow P1 are mixing breaking blue?

**Comment by kriswiner** [comment]
Not sure what you mean...it looks like the colors are all white, I agree.

**Comment by kriswiner** [comment]
You would have to change the current settings to get different colors in
the patterns. WHat I have is simply a place holder, so all colors are white.

**Comment by hwanggz0** [comment]
need to update 0x41 42 43 in order to get the right mixing.
