### ISSUE TITLE
TS T1 T2 T3 T4 TP have to be identical for a pattern to run

### ISSUE THREAD

**Issue by hwanggz0** [kriswiner/IS31FL3194#3]
https://github.com/kriswiner/IS31FL3194/blob/a4e3d77cede73e536f4a38a723b174e8f7eb0be1/IS31FL3194.basic.ino#L126
Do TS T1 T2 T3 T4 TP have to be identical for a pattern to run? In my setup it seems to be the case. As soon as I change one of the timing but not all of them, the pattern would fail to run completely.

**Comment by kriswiner** [comment]
I don't know, better consult the data sheet. I usually do not use this
driver for patterns but just for blinking...

**Comment by hwanggz0** [comment]
need to update 0x41 42 43 in order to get the right mixing and timing.
